### ISSUE TITLE
How do I change wait seconds dynamically?

### ISSUE THREAD

**Issue by snskshn** [Sollimann/bonsai#10]
When I'm using like Wait(1.1), it will wait for 1.1 seconds. I want to change that value without re-constructing whole tree.
Or can Action wait for specific period? I've tried return (Status, f64) with custom f64 value, but it doesn't seem to work.

**Comment by Sollimann** [comment]
> When I'm using like Wait(1.1), it will wait for 1.1 seconds. I want to change that value without re-constructing whole tree. Or can Action wait for specific period? I've tried return (Status, f64) with custom f64 value, but it doesn't seem to work.

Could you provide me an example of what you are trying to achieve? Mabye a code example. Usually there are many ways of constructing the same kind of behavior.

Some context:
* `WaitForever` will always return `(Status, f64) = (Running, 0.0)`
* `Wait(1.1)` will return `(Running, 0.0)` when t < 1.1 and `(Success, t - 1.1)` when t >= 1.1

Thus, you could construct a dynamic wait based on an `Action`, e.g:

```rust
use crate::dynamic_behavior_tests::TestActions::{DynamicWait, Inc};
use bonsai_bt::{Action, Event, State, Success, UpdateArgs, Wait, While, RUNNING};

type Times = Vec<f64>;
/// Some test actions.
#[derive(Clone, Debug)]
enum TestActions {
    /// Increment accumulator.
    Inc,
    ///, Dynamic timing
    DynamicWait(Times),
}

// A test state machine that can increment.
fn game_tick(mut acc: usize, dt: f64, t: &mut f64, counter: &mut usize, state: &mut State<TestActions>) -> usize {
    let e: Event = UpdateArgs { dt }.into();

    let (_s, _t) = state.tick(&e, &mut |args| match &*args.action {
        Inc => {
            acc += 1;
            (Success, args.dt)
        }
        DynamicWait(times) => {
            // reset dynamic timer
            if *counter >= times.len() {
                *counter = 0
            }

            let wait_t = times[counter.to_owned()];

            if *t + dt >= wait_t {
                // in case something blocks the DynamicWait more than what you pre-programmed/pre-compiled
                // your BT will be overdue on time
                let time_overdue = *t + dt - wait_t;
                *counter += 1;
                *t = -dt;
                (Success, time_overdue)
            } else {
                *t += dt;
                RUNNING
            }
        }
    });

    acc
}

#[test]
fn test_alter_wait_time() {
    let a: usize = 0;
    let mut counter = 0;
    let mut timer: f64 = 0.0;
    let rep = While(
        Box::new(Wait(50.0)),
        // first time wait 1.0s, then 2.0s, then 3.0s
        vec![Action(DynamicWait(vec![1.0, 2.0, 3.0])), Action(Inc)],
    );
    let mut state = State::new(rep);

    // time passed=0.0
    // proceed dt=1.0 into the future by invoking game_tick method
    let a = game_tick(a, 1.0, &mut timer, &mut counter, &mut state);
    assert_eq!(a, 1);
    // time passed=1.0
    let a = game_tick(a, 1.5, &mut timer, &mut counter, &mut state);
    assert_eq!(a, 1);
    // time passed=2.5
    let a = game_tick(a, 3.0001, &mut timer, &mut counter, &mut state);
    assert_eq!(a, 2);
    // time passed = 5.50001
    let a = game_tick(a, 7.0001, &mut timer, &mut counter, &mut state);
    assert_eq!(a, 3);
    // time passed = 12.50002
}
```

`PS!` 

This is a pretty dirty example, but you can polish it if you want. You can also use a `Blackboard` to store the state of the BT instead of passing mutual references like `t: &mut f64` and `counter: &mut usize` to the `game_tick`.

**Comment by snskshn** [comment]
Thanks for great example! Now I understand what's the meaning of return value of tick's lambda. What I'm trying to get is condition node and action node. Player is moving toward some coordinate and it takes some time like 100ms. Condition node checks whether the player is moving, and action node actually move players to destination coordinate. While player is moving, condition node have to return running state. After moving is completed, condition node return success with "time_overdue" and action node will move forward.
I think I could implement both condition node and action node using Action with blackboard or argument of game_tick function. Thanks a lot!

**Comment by m0hadang** [comment]
i think this is incorrect 

"*t = -dt;" 

isntead of this is correct ?

"*t -= dt;"
