### ISSUE TITLE
Generate Behavior Tree with Bonsaï from a BT.CPP XML 

### ISSUE THREAD

**Issue by ekkaiasmith** [Sollimann/bonsai#20]
@Sollimann 
[BehaviorTree CPP](https://www.behaviortree.dev/docs/learn-the-basics/main_concepts#instantiate-trees-at-run-time-using-the-xml-format) is a major library for creating Behavior Tree with C++. It provides an XML Schema to serialize BTs and instantiate them at runtime.

```xml
<?xml version="1.0" encoding="ASCII"?>
<!DOCTYPE root>
<root main_tree_to_execute="Usecase1">
  <BehaviorTree ID="Usecase1">
    <Fallback name="">
      <Sequence name="">
        <Action name="" ID="MoveTo" loc_id="kitchen"/>
        <Sequence name="">
          <Action name="" ID="FindObj" obj_id="bottle" obj_p="{object_pose}"/>
          <Action name="" ID="ComputeGraspPose" obj_p="{object_pose}" grasp_p="{grasp_pose}"/>
          <Action name="" ID="OpenGripper"/>
          <Action name="" ID="MoveTo" loc_p="{grasp_pose}" />
          <Inverter>
            <Action name="" ID="CloseGripper"/>
          </Inverter>
        </Sequence>
      </Sequence>
      <Action name="" ID="AskFor" action_id="help"/>
    </Fallback>
  </BehaviorTree>
</root>
```

It will be great for interoperability and to promote Bonsai to have a way to reuse a serialized BT in BT CPP XML format in Bonsai. I worked on a code generation tool called [BT.CPP2Bonsai](https://gitlab.com/ekkaia/btcpp2bonsai) that generates the template code of a behavior tree with Bonsai from such an XML file. I would like to know if you are interested in this feature in the library. If so, I could make a pull request.

**Comment by Sollimann** [comment]
Hey, that is really cool. Great work!

Yes, I would be interested to see how that could look. Feel free to add a PR. In the PR also add:

* Through documentation
* Unit tests and integration tests
* Examples of use (check `/examples` folder)
