### ISSUE TITLE
Let the Blackboard be a generic type

### ISSUE THREAD

**Issue by Sollimann** [Sollimann/bonsai#25]
The current implementation of the `Blackboard` struct in our Rust codebase utilizes a HashMap for key/value storage. While this is functional for many scenarios, there are cases where other data structures might be more appropriate. This issue proposes generalizing the Blackboard struct to allow for various data structures, enhancing its flexibility and potential use cases.

Current Implementation (ref [link](https://github.com/Sollimann/bonsai/blob/55b280e040f29fb5914f60e5b7fa767ec9b45806/bonsai/src/bt.rs#L19C5-L19C5))

```rust
#[derive(Clone, Debug)]
pub struct BlackBoard<K, V>(HashMap<K, V>);
```

The Blackboard struct is currently hard-coded to use HashMap. This limits its use to scenarios best served by a hash map's characteristics (e.g., quick lookups, key/value storage).

**Proposed Change**
I propose that we refactor the Blackboard struct to be generic over its data structure, not just over the key and value types. This would allow users of the Blackboard to select the most appropriate data structure for their specific needs, whether that be a `HashMap`, `BTreeMap`, `Vec`, or any other collection type.

**Suggested Traits for the Data Structure**
* `Iterable` Trait: To allow iteration over the elements.
* `Clone` + `Debug`: These are already in use and should be maintained for consistency and ease of debugging.
* `Serialize` + `Deserialize` (optional): For scenarios where blackboard data needs to be serialized/deserialized, e.g., when saving/loading state or for network communication.

**Default behavior**
Ideally, if a user does not provide a particular data structure, we should default to something like `HashMap<(), ()> = HashMap::new();`

**Comment by Sollimann** [comment]
@kaphula feel free to grab this task if you want to :)

**Comment by Sollimann** [comment]
Added the card in the project Kanban board: https://github.com/Sollimann/bonsai/projects/1#card-91188679

FYA, the Kanban board is a bit out of date

**Comment by Sollimann** [comment]
@kaphula Yea, I agree. The blackboard should not be restricted to the collection type, and users should be able to create any custom struct.

We should aim for the ability to mutate the blackboard within the `bt.state.tick`. On the top of my head I though maybe I would have thought that if we wrap the Blackboard in a reference counter like `std::rc::Rc` before passing into the `bt.state.tick` we should get passed the borrow checker. Worst case it might require an `Rc` and a synchronization primitive like `RwLock` or `Mutex`, however, I don´t think that is necessary as we are not operating with multiple threads.

If that doesn´t work, it might be an alternative to use a global mutable singleton like `once_cell` or `lazy_static` (see https://stackoverflow.com/questions/27791532/how-do-i-create-a-global-mutable-singleton ). But that might push some of the burden onto the user of the lib which we want to avoid. We want to hide complexity from the user as much as possible. I think the best case scenario for a library is something like [rayon](https://github.com/rayon-rs/rayon) which is very simple to use and all the complexity of data parallelism is hidden away from the user.

What do you think? :)

**Comment by kaphula** [comment]
I went for a simpler solution since I am not very used to using `RwLock` or `Mutex` because there's almost always been an alternative solution available. In the PR I added a wrapper `tick` function to the `BT` struct so that the blackboard can be passed to the callback under the hood as mutable reference. This change requires that the user uses `bt.tick(...)` instead of `bt.state.tick(...)`.

https://github.com/Sollimann/bonsai/pull/26

I also tried another version where the blackboard reference is stored into `ActionArgs` struct, but I feel this version ended up being more messy. It's on my fork [as a branch](https://github.com/kaphula/bonsai/tree/generic-blackboard-action-args) anyway if you want to take a look. Both versions should compile and pass all tests.

**Comment by kaphula** [comment]
Oh yeah I forgot about the traits. Did you intend that the `Serialize` + `Deserialize` traits would be some kind of a crate level optional feature (I have no idea if this is even possible)?

**Comment by Sollimann** [comment]
@kaphula actually, after thinking a bit more about it, I think we can drop the `Serialize` and `Deserialize` traits as they would make the blackboard more constrained. E.g if you include 3rd party crate types that does not include `Serialize` and `Deserialize` you would not be able to embed them into your blackboard type.
