### ISSUE TITLE
Remove front page readme code example 

### ISSUE THREAD

**Issue by kaphula** [Sollimann/bonsai#27]
I feel like the example code given on the front page or readme should be implemented as fully working code example, removed completely or a link should be given to one of the currently existing examples. 

The reason being that since the code is not in any way connected to the build system and tests, it can easily get out of date and confuse new users. It also did not help me much in understanding how to use this library initially since I could not just copy the code to a new empty Rust project and run it without getting errors. This is the reason why I implemented the simple NPC example to aid my own understanding of the library.

**Comment by Sollimann** [comment]
Thanks for pointing out, and I totally agree. Which documentation did you find most useful? and did you find any documentation to be superflous? I'm thinking about making the README.md a bit more lean and e.g removing the example code you are referring to and just linking to the `/examples` folder instead. Could also just make a very simple and short example like your `/simple_npc_ai` example, but mabye even shorter. What do you think?

**Comment by kaphula** [comment]
I think the documentation is fine. If you are new to the concept of behavior trees and read the main page of this crate it may be hard to reason if this crate and behavior trees in general are useful for your own needs. Therefore simple examples where you get to see immediately how the code is executed line by line is most likely the best and quickest way to understand the basics. The documentation then serves secondary purpose when you want to explore the details. This is what I like about Rust's official documentation, simple code examples are always there to get you going fast.

I could possibly write a new example at some point which would focus on being minimal while making use of couple different actions. For anyone else reading this, feel free to try this as this could be a good exercise to learn the library and contribute to it.

I also submitted bonsai-bt to [Are we game yet?](https://arewegameyet.rs/)'s AI section so perhaps it will help to gain more eyes to the project.
