### ISSUE TITLE
Separate graph drawing functionality from BT structure

### ISSUE THREAD

**Issue by kaphula** [Sollimann/bonsai#29]
As far as I understand, the `graph` field in `BT` struct is only utilized when and if someone wants to create a visual graph from the behavior tree. This means that everytime a behavior tree is constructed, the data related to drawing graphs gets constructed as well even though it may be useless. Would it not make sense to separate the graphing data away from the behavior tree's struct and perhaps construct the needed graph data on the fly when someone  wishes to make use of the graph?

Although it would probably be advised to cache your behavior trees in advance and clone them later during a life time of an application, if someone wishes to build behavior trees dynamically many times during a single frame of a game for example, getting rid of the graph stuff makes even more sense since it seems to be the "heaviest part" in behavior tree constructor.

**Comment by Sollimann** [comment]
Yes, good point. Currently graph build is only used for visualisation purpose which is useful when debugging your behavior tree. I think it the graph construction can be moved from the BT constructor function `new` to e.g the `get_graphviz` function
